config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  {
    sessions: 'users/sessions'
  }

  root 'home#index'

  resources :user do 
    resources :recipes
  end
  resources :home,:user
  resources :recipes
  resources :comments
  resources :likes, only: [:create, :destroy]
  get '/search' , to: "home#search"

  devise_scope :user do 
     get '/users/sign_out' => 'devise/sessions#destroy' 
   end
   namespace :api do 
    namespace :v1 do 
      resources :user,:recipes,:comments,:likes
      post "/login", to: "user#login"
      get "/logout", to: "user#logout"
  
    end
   end
end

# namespace :api do
#   namespace :v1 do
#     resources :events, :users, :organizers, :attenders, :tickets, :home
#     post "/login", to: "users#login"
#     get "/logout", to: "users#logout"

#     resources :events do
#       resources :comments, :tickets
#     end
#   end
# end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # validates :name, :description, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :file, dependent: :destroy
  def self.ransackable_attributes(auth_object = nil)
    %w(name)
  end
 
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < ApiController
  # protect_from_forgery with: :null_session
  before_action :authenticate_request
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /api/v1/recipes
  def index
    @recipes = Recipe.all
    render json: @recipes
  end

  # GET /api/v1/recipes/:id
  def show
    if @recipe
      render json: @recipe
    else
      render json: {error:"not found"}, status: :not_found
    end
  end

  # POST /api/v1/recipes
  def create
    if current_user
      @recipe = Recipe.create(recipe_params)
      @recipe.user_id = current_user.id

      respond_to do |format|
        if @recipe.save
          format.json { render json: @recipe, status: :created, location: @recipe }
        else
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # GET /api/v1/recipes/:id/edit
  def edit
    render json: @recipe
  end

  # PATCH/PUT /api/v1/recipes/:id
  def update
    if @recipe.user_id == current_user.id
      if @recipe.update(recipe_params)
        render json: @recipe
      else
        render json: { errors: @recipe.errors.full_messages }, status: :unprocessable_entity
      end
    else
      render json: { error: "You are not authorized to update this recipe." }, status: :unauthorized
    end
  end

  # DELETE /api/v1/recipes/:id
  def destroy
    if @recipe.user_id == current_user.id
      @recipe.destroy
      head :no_content
    else
      render json: { error: "You are not authorized to delete this recipe." }, status: :unauthorized
    end
  end

  private

  
  def set_recipe
    @recipe = Recipe.find_by(id: params[:id])
  end

  def recipe_params
    params.permit(:name, :description, :ingredient, :file)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

 
def index
   @recipes = Recipe.all 

end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipes_path #index of all recipes 
    else
      render :new, status: :unprocessable_entity
    end
  end
  

  def edit
    @recipe = Recipe.find(params[:id])
  end
  

  def update
    @recipe = Recipe.find(params[:id])
  
    if @recipe.user == current_user
      if @recipe.update(recipe_params)
        redirect_to recipes_path
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to @recipe
    end
  end
  
  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
      @recipe.destroy
      redirect_to recipes_path, status: :see_other
    else
      flash[:alert] = "You are not authorized to delete this recipe."
      redirect_to @recipe
    end
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :description, :ingredient, :file)
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% form.object.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <%= form.label :description %><br>
  <%= form.text_area :description %>
  <% form.object.errors.full_messages_for(:description).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>
 <div>
  <%= form.label :ingredient %><br>
  <%= form.text_area:ingredient%>
  <% form.object.errors.full_messages_for(:ingredient).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>
<div>
  <%= form.label :file %><br>
  <%= form.file_field :file %>
  <% form.object.errors.full_messages_for(:file).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<div class="container-fluid p-4 d-flex flex-wrap text-center justify-content-center align-items-center">
  <% current_user.recipes.each do |recipe| %>
   <% cache recipe do %>
   
  <% if user_signed_in? %>
    <div class="card m-3" style="width: 16rem;">
      <% if recipe.file.attached? && recipe.file.image? %>
        <%= image_tag recipe.file, class: "card-img-top" %>
      <%else%>
      <img src="/images/food1.jpeg" class="card-img-top" alt="...">
      <%end%>
      <div class="card-body">
        <h5 class="card-title"><%=  recipe.name %></h5>
        <%= link_to "view details", recipe , class:"btn btn-primary btn-sm"%>
       
      </div>
    </div>
  <% end %>
  <% end %>

<% end %>



</div>


  

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<div class="container mt-3">
 <div class="row p-4 ">
  <div class="col-4 ">
    <div class="img-fluid border">
      <% if @recipe.file.attached? %>
    <div class="recipe-media">
      <% if @recipe.file.image? %>
        <%= image_tag @recipe.file, class: "recipe-image img-fluid " %>
      <% elsif @recipe.file.video? %>
      <%= video_tag url_for(@recipe.file), class: "recipe-video video-fluid", controls: true, style: "width: 100%; height: auto;" %>
      <% end %>
    </div>
  <% end %>

    </div>
  </div>
  <div class="col-8">
    <h2><%= @recipe.name %></h2>
    <p class="recipe-description"><%= @recipe.description %></p>
    <h3>Main Ingredients</h3>
    <p class="recipe-ingredient"><%= @recipe.ingredient %></p>
   <div class="d-flex">
   
      <% if current_user == @recipe.user %>
     
        <%= link_to "Edit", edit_recipe_path(@recipe), class:"btn btn-success mx-1" %>
        <%= button_to 'Destroy', recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mx-1" %>
      <% else %>
        <%= link_to 'Add Comment', new_comment_path(recipe_id: @recipe.id), class: "btn btn-success" %>
        <%= link_to "View Comments", comments_path(recipe_id: @recipe.id), class: "btn btn-info" %>
        <%= link_to "Back", :back, class: "btn btn-primary mx-1" %>
      <% end %>
  
      <%= @recipe.likes.count %> likes
      <% like = current_user.likes.find_by(recipe: @recipe) %>
      <% if like.nil? %>
        <%= button_to 'Like', likes_path, params: { like: { recipe_id: @recipe.id } }, method: :post, class: "btn btn-primary mx-1" %>
      <% else %>
        <%= button_to 'Unlike', like_path(like), method: :delete, class: "btn btn-danger mx-1" %>
      <% end %>
    
   </div>
  </div>
 </div>
</div>