config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  {
    sessions: 'users/sessions'
  }

  root 'home#index'

  resources :user do 
    resources :recipes
  end
  resources :home,:user
  resources :recipes
  resources :comments
  resources :likes, only: [:create, :destroy]
  get '/search' , to: "home#search"

  devise_scope :user do 
     get '/users/sign_out' => 'devise/sessions#destroy' 
   end
   namespace :api do 
    namespace :v1 do 
      resources :user,:recipes,:comments,:likes
      post "/login", to: "user#login"
      get "/logout", to: "user#logout"
  
    end
   end
end

# namespace :api do
#   namespace :v1 do
#     resources :events, :users, :organizers, :attenders, :tickets, :home
#     post "/login", to: "users#login"
#     get "/logout", to: "users#logout"

#     resources :events do
#       resources :comments, :tickets
#     end
#   end
# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #  @recipes = Recipe.all 
     @q = Recipe.ransack(params[:q])
     @recipes = @q.result
  end
  def search
    if 
    @query = params[:query]
    @recipe = Recipe.find_by(name: @query)
    redirect_to recipe_path(@recipe)
    else
      puts "not found"
    end
  end
  
end

app/views/home/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
  <div class="container-fluid">
        <a class="navbar-brand" href="/home">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <%if user_signed_in? %><br>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/users/sign_out">Log-out</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/users/edit">Edit Profile </a>
        </li>

        <li class="nav-item">
        <%= link_to "My Recipes", "/recipes", class: "nav-link active" %>
        </li>

          <li class="nav-item">
        <%= link_to "All Recipes", "/home", class: "nav-link active" %>
        </li>
 


        <li class="nav-item">
        <%= link_to "Create Recipe", new_recipe_path(@recipe), class: "nav-link active" %>
        </li>
        <%else%>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/users/sign_in">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/users/sign_up">Sign-up</a>
        </li>
        <%end%> 
      </ul>
         <%if user_signed_in? %><br>
      <%# <form class="d-flex" method = "GET" action = "/search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name = "query" method = "GET">
        <button class="btn btn-outline-success" type="submit">Search</button> %>
        <%= search_form_for @q, url: "/home", method: :get do |f| %>
  <%= f.label :name_cont, 'Full Name' %>
  <%= f.search_field :name_cont %>
  <%= f.submit %>
<% end %>
<% end %>

      </form>
    </div>
  </div>
</nav>
    </body>
</html>

app/views/home/index.html.erb
<%# <%= search_form_for @q, url: "/home", method: :get do |f| %>
<!-- 
<h3><%= t(:hello)%></h3> -->

<% if user_signed_in? %>
<div class="container-fluid p-4 d-flex flex-wrap text-center justify-content-center align-items-center">
  <% @recipes.each do |recipe| %>
    <div class="card m-3" style="width: 16rem;">
      <% if recipe.file.attached? && recipe.file.image? %>
        <%= image_tag recipe.file, class: "card-img-top" %>
      <%else%>
      <img src="/images/food1.jpeg" class="card-img-top" alt="...">
      <%end%>
      <div class="card-body">
        <h5 class="card-title"><%=  recipe.name %></h5>
        <%= link_to "view details", recipe , class:"btn btn-primary btn-sm"%>
       
      </div>
    </div>
  <% end %>
</div>
<%else%>
<img height="720" src="/assets/recipe.webp" width="100%" height="70%" />

<% end %>

  